### ISSUE TITLE
PHP Warning: Illegal string offset '4.1268548415' in BCMathService.php on line 91

### ISSUE THREAD

**Issue by shine-on** [stephen-hill/base58php#12]
master @ 430ba54a3c3144f03e8a03e1679e672c688cb8a6

3.19.0-26-generic #28-Ubuntu SMP Tue Aug 11 14:16:32 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 15.04
Release:    15.04
Codename:    vivid

PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans

```php
// If there's still a remainder, append it
if ($decimal > 0) {
    $output .= $this->alphabet[$decimal];    // line 91
}
```

**Comment by stephen-hill** [comment]
Hi,

I just have a few follow-up questions.

What version of this library are you using?
What was the input string to the `encode()` method?
What OS are you using?

Also, if possible, could you write me a PHP script that replicates this problem - because if I cannot reproduce this error, I cannot fix it.

Many Thanks
Stephen

**Comment by shine-on** [comment]
Updated original issue. Now trying to isolate offending code.

**Comment by shine-on** [comment]
http://php.net/manual/en/function.bcdiv.php

Signature:
```php
string bcdiv ( string $left_operand , string $right_operand [, int $scale = int ] )
```

Return value:
```php
Returns the result of the division as a string, or NULL if right_operand is 0.
```

http://php.net/language.types.string

"As of PHP 5.4 string offsets have to either be integers or integer-like strings, otherwise a warning will be thrown. Previously an offset like "foo" was silently cast to 0."

```php
<?php
$str = 'abc';

var_dump($str['1']);
var_dump(isset($str['1']));

var_dump($str['1.0']);
var_dump(isset($str['1.0']));

var_dump($str['x']);
var_dump(isset($str['x']));

var_dump($str['1x']);
var_dump(isset($str['1x']));
?>
```

Output of the above example in PHP 5.3:

```
string(1) "b"
bool(true)
string(1) "b"
bool(true)
string(1) "a"
bool(true)
string(1) "b"
bool(true)
```

Output of the above example in PHP 5.4:

```
string(1) "b"
bool(true)

Warning: Illegal string offset '1.0' in /tmp/t.php on line 7
string(1) "b"
bool(false)

Warning: Illegal string offset 'x' in /tmp/t.php on line 9
string(1) "a"
bool(false)
string(1) "b"
bool(false)
```

Library assumes it can use $decimal as an index, but it can't because bcdiv return is a string:

```php
while ($decimal >= $this->base) {
    $div = bcdiv($decimal, $this->base);
    $mod = bcmod($decimal, $this->base);
    $output .= $this->alphabet[$mod];
    $decimal = $div;
}

// If there's still a remainder, append it
if ($decimal > 0) {
    $output .= $this->alphabet[$decimal];    // line 91
}
```

**Comment by stephen-hill** [comment]
Hi

The problem here as far as I can see, is that `bcdiv` should only be returning integers.
Where as it appears to be returning a float. Also, I can't see how it could return anything other than a value between 58 and zero.

Could you please provide the input string that threw the original error message?

Eg: `$base58->encode('Hello World');`

Without that, I cannot test anything. I can only make assumptions.

Also, did you change the alphabet, and if so, what to?

Many Thanks
Stephen

**Comment by stephen-hill** [comment]
If I get a chance tonight, I will install 15.04 and run the unit tests.

But it still stands that I need the original input string to the `encode()` method. Without that, I don't think I can successfully debug the problem.

Issue #10 is the same as this. The input string that caused the error was never provided, so the problem was never fixed.

Cheers
Stephen

**Comment by shine-on** [comment]
I've tried very hard to develop a test case, but failed to repeatably reproduce. The only thing I should mention, the problem randomly occurs only in apache mode and never in cli.

Found similar issue https://bugs.php.net/bug.php?id=68837 where expected integer arithmetic result looks not really integer.

**Comment by stephen-hill** [comment]
Well thank you very much for trying to reproduce the error.

I would suggest, if you can, using GMP instead of BCMath because it appears not to have this problem and it's faster.

I'm also thinking of removing BCMath support in version 2.0 of this library to simplify the code.

Cheers
Stephen

**Comment by shine-on** [comment]
Hit it again:

```
[Thu Sep 03 23:26:09.279469 2015] [:error] [pid 10543] [client 127.0.0.1:36348]
PHP Warning:  Illegal string offset '1.1200738330' in -=censored=-/BCMathService.php
on line 91
```

But if I try to run same action with same encode argument it doesn't show up. Very strange.

Action is using something like this:

```php
$options = (object) [
    'url' => 'url goes here'
];

$base58->encode(json_encode($options));
```

URLs in question are regular web links with nothing special at all.
